_data_hub_data_importer_data_object_admin:
    resource: "@PimcoreDataImporterBundle/Controller/ConfigDataObjectController.php"
    type:     annotation
    options:
        expose: true

_data_hub_data_importer_data_object_push:
    resource: "@PimcoreDataImporterBundle/Controller/PushImportController.php"
    type:     annotation
