
name: "Codeception Tests"

on:
    schedule:
        - cron: '0 3 * * 1,3,5'
    pull_request:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"
    push:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"

env:
    PIMCORE_PROJECT_ROOT: ${{ github.workspace }}
    APP_ENV: test
    PIMCORE_TEST: 1
    PIMCORE_TEST_DB_DSN: "mysql://root@127.0.0.1:33006/pimcore_test"
    PIMCORE_ELASTIC_SEARCH_HOST: 'localhost:39200'

jobs:
    codeception-tests:
        name: "Codeception tests"
        runs-on: "ubuntu-20.04"
        continue-on-error: ${{ matrix.experimental }}
        strategy:
            matrix:
                include:
                    - { php-version: 8.0, database: "mariadb:10.7", pimcore_version: "", dependencies: highest, experimental: false }
                    - { php-version: 8.1, database: "mariadb:10.7", pimcore_version: "", dependencies: highest, experimental: false }
                    - { php-version: 8.1, database: "mariadb:10.7", pimcore_version: "11.x-dev", dependencies: highest, experimental: true }
        services:
            mariadb:
                image: "${{ matrix.database }}"
                ports:
                    - 33006:3306
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes

        steps:
            - name: "Checkout code"
              uses: "actions/checkout@v2"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  coverage: "none"
                  extensions: imagick
                  ini-values: display_errors=On, display_startup_errors=On, error_reporting=32767
                  php-version: "${{ matrix.php-version }}"

            - name: Verify MariaDB connection
              run: |
                  cp .github/ci/files/.my.cnf ~/.my.cnf
                  while ! mysqladmin ping --silent; do
                    sleep 1
                  done

            - name: "Setup Pimcore environment"
              run: |
                  mysql -e "CREATE DATABASE pimcore_test CHARSET=utf8mb4;"
                  chmod 755 .github/ci/scripts/setup-pimcore-environment.sh
                  .github/ci/scripts/setup-pimcore-environment.sh

            - name: "Update Pimcore version"
              env:
                  PIMCORE_VERSION: "${{ matrix.pimcore_version }}"
              run: |
                  if [ ! -z "$PIMCORE_VERSION" ]; then
                        composer require --no-update pimcore/pimcore:"${PIMCORE_VERSION} as 10.99.9"
                  fi    

            - name: "Install dependencies with Composer"
              uses: "ramsey/composer-install@v1"
              with:
                  dependency-versions: "${{ matrix.dependencies }}"

            - name: "Run Codeception"
              run: "vendor/bin/codecept run -c . -vvv --json"
